pipeline {
    agent none
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dh_react')
    }
    stages {
         stage('Checkout'){
            agent any
            steps{
                //Changez avec votre lien github
                git branch: 'main', url: 'https://github.com/123456789arij/projetdevopsreact.git'
            }
        }
        stage('Init'){
            agent any
            steps{
            sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }


         stage('Build frontend') {
               agent any
            when{
                changeset "**/react/*.*"
                beforeAgent true
            }
            steps {
                dir('react'){
                    sh 'docker build -t arijabid/react:$BUILD_ID .'
                    sh 'docker push arijabid/react:$BUILD_ID'
                    sh 'docker rmi arijabid/react:$BUILD_ID'
                    sh 'docker logout'
                }
            }
        }
        stage('Build backend') {
              agent any
            when{
                changeset "**/nest/*.*"
                beforeAgent true
            }
            steps {
                dir('nest'){
                    sh 'docker build -t arijabid/nest:$BUILD_ID .'
                    sh 'docker push arijabid/nest:$BUILD_ID'
                    sh 'docker rmi arijabid/nest:$BUILD_ID'
                    sh 'docker logout'
                }
            }
        }

    }
}