apiVersion: v1
kind: Service
metadata:
  labels:
    app: ELearningManagement - backend-service
  name: backend
spec:
  ports:
  - port: 8090
  selector:
    service: ELearningManagement - backend
  type: LoadBalancer